### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by james-ingold** [serverless/serverless-kubeless#138]
Is there any way to get typescript support? I've used the serverless-plugin-typescript before but it doesn't seem to work with serverless-kubeless. 
https://github.com/prismagraphql/serverless-plugin-typescript

Anyone using this plugin with typescript or have recommendations? 

Thanks,

James

**Comment by alexander-alvarez** [comment]
Are you able to build before running `sls deploy`?
Then you can include the `dist/` or whatever your `compilerOptions.outDir` is, and everything should work since it's javascript.
