### ISSUE TITLE
Q: NATS support

### ISSUE THREAD

**Issue by nea** [serverless/serverless-kubeless#142]
Hey

As kubeless is supporting NATS now, is there also support planned via serverless-kubeless? Right now, if I add a trigger event in the serverless.yml it implicitly tries to `Deploying Kafka trigger` and fails obviously as I only have a NATS running.

Thanks a lot in advance

**Comment by andresmgot** [comment]
Hi,

Unfortunately that is not supported yet. If you want to contribute the project with that feature it will be more than welcome :). Basically we would need to mimic the same logic than with the KafkaTrigger but generate a NatsTrigger instead. We would need to have a field in the serverless.yaml as well to choose between Kafka or NATS (defaulting to Kafka).

**Comment by nea** [comment]
Hey @andresmgot 

Ok, got it. Just wanted to check up on it. If I find time I will look into it.

But big thanks for giving me a heads up.


Thanks
