### ISSUE TITLE
Q: Serverless two functions, endless hanging in status Pending

### ISSUE THREAD

**Issue by nea** [serverless/serverless-kubeless#146]
Hi 

I am facing the issue that I am developing a multi-function app and started with one function, several updates etc. testing worked fine.

Then I added a second function. The initial deployment worked fine. But when I want to update the second function it always hangs endlessly in a pending state and nothing happens. I can update the first one, but the second one does not work.

I oriented on the RESTful blog example structure-wise.

Any idea how I could debug that?

Thanks a lot

**Comment by andresmgot** [comment]
Hi, when you say it's pending you mean that the status of the pod running the function is "Pending"? If that is the case you can discover the reason executing:

```
kubectl describe pod -l function=<your_function>
```

If your function doesn't have a pod you can check the controller logs executing:

```
kubectl logs -n kubeless -l kubeless=controller
```

I hope that helps,

**Comment by nea** [comment]
Thanks @andresmgot , I was looking for such commands to better get and understand the issues. Thanks.

**Comment by andresmgot** [comment]
For the record there is a bit of documentation for debugging functions: https://kubeless.io/docs/debug-functions/
