### ISSUE TITLE
NPM Repo is out of date

### ISSUE THREAD

**Issue by mikefarah** [serverless/serverless-kubeless#154]
NPM version is at version 0.4.4 whereas 0.5.1 has been out for a couple of months...

Really want that #148 fix so I guess I'll temporarily point to the git tag in npm

**Comment by andresmgot** [comment]
Sorry @mikefarah, where are you seeing that version, in the examples or somewhere else? Can you send a PR updating that version?

**Comment by andresmgot** [comment]
Ah, I see that the version has not been updated in the npmjs.org page. That's a bug in our release process. I will try to fix it.
