### ISSUE TITLE
Support for securing HTTP functions

### ISSUE THREAD

**Issue by mpalumbo7** [serverless/serverless-kubeless#169]
This is a request for a new feature.

Kubeless supports securing HTTP functions exposed via an Ingress. See https://kubeless.io/docs/http-triggers/ for more information.

Is this on your roadmap?

**Comment by andresmgot** [comment]
Right now we don't have the resources to work on that. If you want to tackle it that'd be great we can help you with the implementation/reviews if needed.

**Comment by mpalumbo7** [comment]
After a little research, I think this can be accomplished entirely via the ‘additionalAnnotations’ field. 

The [ingress-nginx/docs/examples/Auth/basic](https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/auth/basic/README.md) detail how to use an existing secret to apply basic authentication to an Ingress route using only annotations. 

E
