### ISSUE TITLE
Unable to use kubeless installed in any namespace other than 'kubeless'

### ISSUE THREAD

**Issue by d0x2f** [serverless/serverless-kubeless#174]
You can see here the default namespace to look for the config-map is 'kubeless':

https://github.com/serverless/serverless-kubeless/blob/master/lib/config.js#L25

And you can see here that the Config object is constructed with no other options given:

https://github.com/serverless/serverless-kubeless/blob/master/deploy/kubelessDeploy.js#L84

Thus the config-map is only ever able to be fetched from the 'kubeless' namespace.

**Comment by andresmgot** [comment]
Yes, that's correct. Would you able to send a PR to fix that? The easiest solution would be to read an env var at that point. The `kubeless` CLI uses `KUBELESS_NAMESPACE` for that.

**Comment by d0x2f** [comment]
Sure I'll give it a go.
