### ISSUE TITLE
NodeJs HTTP Response Code is always 200

### ISSUE THREAD

**Issue by raul-madrigal** [serverless/serverless-kubeless#180]
The kubeless nodejs runtime is always returning HTTP code 200. Besides `context` is always empty, what is that parameter for?

## Expected Behavior
```
module.exports = {
  hello(event, context) {
    return {'statusCode': 403, 'message': 'Hello world'}
  },
}
```

`curl -i http://localhost/hello`, should return:

```
....
HTTP/1.1 403 Forbidden
....
{"statusCode": 403, "message": "Hello world"}
```

## Current Behavior
`curl -i http://localhost/hello`, returns:

```
....
HTTP/1.1 200 OK
....
{"statusCode": 403, "message": "Hello world"}
```

**Comment by andresmgot** [comment]
hi @raul-madrigal,

For the case of the NodeJS runtime, you have the value `event.extensions.response` available. This is the ExpressJS response that will be used. You can use `event.extensions.response.status(403);` to set the status code.

**Comment by raul-madrigal** [comment]
Thanks @andresmgot, I confirm that works.
