### ISSUE TITLE
Inject kubernetes secrets to a function definition

### ISSUE THREAD

**Issue by raul-madrigal** [serverless/serverless-kubeless#197]
Currently, I'm using https://github.com/Jimdo/serverless-dotenv to manage environment variables and secrets in a NodeJS runtime. The plugin works as expected and publishes the variables into the `process.env`. The problem is that anyone with permissions to describe the Kubernetes resources, for example, the function deployment can see in plain text the variables that were added using the dotenv file.

Therefore, is there any example or guidance on how to use the serverless-kubeless to inject a Kubernetes secret and consume it in a NodeJs runtime function?

**Comment by andresmgot** [comment]
Yes, unfortunately there are no docs for this. You can specify an array of secrets in your function and the will be mounted in your function using the path `/<secret-name>`. You can see the code related to that here:

https://github.com/serverless/serverless-kubeless/blob/master/lib/deploy.js#L161

Note that you need to create the secrets before-hand.

**Comment by raul-madrigal** [comment]
Thanks for pointing me in the right direction. Here is what I did to keep the same dotenv file usage.

1. Created a K8s secret: 
```
kubectl create secret generic secret-dotenv-file  --from-file=.env
```

2. Added the secret key into the provider definition in the `serverless.yml` file:
```
provider:
  name: kubeless
  runtime: nodejs10
  ....

  secrets:
    - secret-dotenv-file
```

3. Inside the pod:
```
require('dotenv').config({
  path: '/secret-dotenv-file/.env',
})
```

You can mark this issue as resolved. Thanks again for helping out.

**Comment by raul-madrigal** [comment]
I opened this PR to include the above documentation in this repository https://github.com/serverless/serverless-kubeless/pull/198.
