### ISSUE TITLE
keep track of google provider verification issue

### ISSUE THREAD

**Issue by sebgoa** [serverless/serverless-kubeless#2]
add reference issue from upstream

**Comment by ngtuna** [comment]
https://github.com/serverless/serverless/issues/3611

**Comment by sebgoa** [comment]
@andresmgot this one is an upstream "issue" in serverless. Maybe you can help fix it so that our function metadata does not have to specify a provider "google".

**Comment by sebgoa** [comment]
this is PRd upstream:
https://github.com/serverless/serverless/pull/3941

**Comment by andresmgot** [comment]
This was implemented at #44 and it is available in the version 0.1.8
