### ISSUE TITLE
Deploy of functions with runtime that has no depName

### ISSUE THREAD

**Issue by lorenzo-ange** [serverless/serverless-kubeless#202]
Hello,
I'm trying to deploy a function with a runtime that has no dependencies file and I'm getting this error:
`The runtime <RUNTIME_NAME> is not supported yet`

The exception seems to be thrown [here](https://github.com/serverless/serverless-kubeless/blob/a31d1282213763ec4ada914324d254291699d9d9/lib/helpers.js#L222) :
```
function getRuntimeDepfile(runtime, configMap) {
  const runtimesInfo = configMap.get('runtime-images', { parse: true });
  let depFile = null;
  _.each(runtimesInfo, r => {
    if (runtime.match(r.ID)) {
      depFile = r.depName;
    }
  });
  if (!depFile) {
    throw new Error(
      `The runtime ${runtime} is not supported yet`
    );
  }
  return depFile;
}
```
As stated [here](https://github.com/kubeless/runtimes/blob/master/DEVELOPER_GUIDE.md) the dependency file is not mandatory in Kubeless runtimes.

Can we remove this check?

Thank you for your work,
Lorenzo

**Comment by andresmgot** [comment]
Indeed, that seems like the wrong place for that check. Could you send a PR to remove that check?

**Comment by lorenzo-ange** [comment]
Sorry @andresmgot for the late response. The PR fixes this issue.

Thank you,
Lorenzo
