### ISSUE TITLE
Manual ingress vs HTTP Trigger

### ISSUE THREAD

**Issue by faxioman** [serverless/serverless-kubeless#205]
I see that the plugin is directly creating an http ingress instead of creating a kubeless http trigger.
Is there a chance that this odd behaviour will change in the near future?

Thanks!

**Comment by faxioman** [comment]
Ok, the reason for this behaviour is now clear:

```
case 'http':
      // TODO: Rely on Kubeless httptrigger object when it support paths
      break;
```

Has this implementation already started?

**Comment by andresmgot** [comment]
yes, that's correct but we never had the time to implement that. Accepting contributions here!

**Comment by faxioman** [comment]
@andresmgot ok, I'm preparing a pull request

**Comment by faxioman** [comment]
Ok, pull request pushed: https://github.com/serverless/serverless-kubeless/pull/206

**Comment by faxioman** [comment]
#206 merged
