### ISSUE TITLE
tlsConfig not working v:0.10.0 

### ISSUE THREAD

**Issue by simodev25** [serverless/serverless-kubeless#212]
**-"serverless-kubeless": "^0.10.0":**
- kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
-serverless.yml

```
service:
  name: cert-manager-https

plugins:
  - serverless-kubeless

provider:
  name: kubeless
  hostname: example.com
  runtime: nodejs8
  ingress:
    additionalAnnotations:
      kubernetes.io/tls-acme: "true"
    tlsConfig:
      - hosts:
          - "example.com"
        secretName: ingress-example-com-certs

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
```

Ingress resulta 👎 
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: hello
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/hello
  uid: ba4ade8b-068b-45c2-8dfd-bbc6ed51f72e
  resourceVersion: '424788'
  generation: 1
  creationTimestamp: '2020-07-17T14:20:05Z'
  labels:
    created-by: kubeless
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /
  ownerReferences:
    - apiVersion: kubeless.io/v1beta1
      kind: HTTPTrigger
      name: hello
      uid: 49dc4c34-c006-4a62-8955-bb127ccbae69
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /hello
            backend:
              serviceName: hello
              servicePort: 8080

```

 **-"serverless-kubeless": "^0.9.3":**
Ingress resulta 👍 
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cert-manager-https
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/cert-manager-https
  uid: ecb491d1-4983-4864-92d9-b94856b50dec
  resourceVersion: '427092'
  generation: 1
  creationTimestamp: '2020-07-17T14:30:54Z'
  annotations:
    kubernetes.io/tls-acme: 'true'
    undefined.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - example.com
      secretName: ingress-example-com-certs
  rules:
    - host: example.com
      http:
        paths:
          - path: /hello
            backend:
              serviceName: hello
              servicePort: 8080


```

**Comment by andresmgot** [comment]
Hi @simodev25, 

Yes, after https://github.com/serverless/serverless-kubeless/pull/206 the ingress object is created by Kubeless rather than by the serverless plugin. Because of that, the description needs to change a bit. What I believe you need is:

```
service:
  name: cert-manager-https

plugins:
  - serverless-kubeless

provider:
  name: kubeless
  hostname: example.com
  runtime: nodejs8
  ingress:
    hostname: example.com
    tls: true
    enableTlsAcme: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
```

Please @faxioman correct me if I am wrong. I think we missed updating the documentation.

**Comment by simodev25** [comment]
thank you @andresmgot
and for the secretName I put it where?

**Comment by faxioman** [comment]
@andresmgot Ops, my bad. Anyway, this is the only documentation I found about the previous ingress configuration:

https://www.serverless.com/framework/docs/providers/kubeless/guide/functions/

How can we update this doc?

**Comment by faxioman** [comment]
@andresmgot I think I've found the repo:

https://github.com/serverless/serverless/tree/master/docs/providers/kubeless

Could I propose a pull-request?

**Comment by faxioman** [comment]
@simodev25 until we update the doc, the option you're searching for is **tlsSecretName**

**Comment by simodev25** [comment]
thank you @faxioman

**Comment by andresmgot** [comment]
Thanks for jumping in @faxioman. Yes, that's the documentation we need to update :) I am not a maintainer in that repo but ping me if you create a PR to review it.
