### ISSUE TITLE
Is it supports kubernetes deployment annotations like ingress?

### ISSUE THREAD

**Issue by kingpeti** [serverless/serverless-kubeless#226]
I have to annotate all functions(lots) with service mesh in deployment.
How to do that?

**Comment by andresmgot** [comment]
Hi, it's possible to configure Kubeless to modify the default Deployment template for all functions, not sure if that would work for you. More info here: https://kubeless.io/docs/function-controller-configuration/

**Comment by kingpeti** [comment]
Thanks, the `ConfigMap` `kind: Function` part is that I need but can I configure that in `serverless.yml`?

**Comment by andresmgot** [comment]
At this moment, annotations cannot be declared globally in the `serverless.yml` file. Only the properties: `runtime`, `memorySize`, `timeout`, `cpu`, `affinity`, `tolerations`, `volumes` and `volumeMounts` can be defined per provider.

**Comment by kingpeti** [comment]
Thanks. I'll be looking forward to using this annotation feature.
