### ISSUE TITLE
Add event type

### ISSUE THREAD

**Issue by sebgoa** [serverless/serverless-kubeless#25]
We should be able to define whether the functions is http or event triggered.

There does not seem to be a standard among the current providers but there is an `event` section, in which we can define `http` and `trigger`...need to check exact syntax.

```
events:
  - http
```

or:
```
events:
  - stream: <topic name>
```

Something like that we need to investigate the best schema for it.

**Comment by andresmgot** [comment]
This was implemented in #40 and is already available
