### ISSUE TITLE
create function template

### ISSUE THREAD

**Issue by ngtuna** [serverless/serverless-kubeless#3]
serverless provides a command to create function template

```
$ serverless create --template aws-python --path my-service
```

We should also have

```
$ serverless create --template kubeless-python --path my-service
```

Or kubernetes-python ?

**Comment by sebgoa** [comment]
we need to check if these are global to serverless or can be specific to our plugin.

**Comment by sebgoa** [comment]
This is PRd upstream:

https://github.com/serverless/serverless/pull/3970

**Comment by sebgoa** [comment]
3970 got merged so I am closing this
