### ISSUE TITLE
Add missing serverless calls

### ISSUE THREAD

**Issue by sebgoa** [serverless/serverless-kubeless#4]
we need to add:

* create (maybe)
* install (maybe)
* invoke
* logs
* info

See openwhisk coverage: https://serverless.com/framework/docs/providers/openwhisk/cli-reference/install/

**Comment by andresmgot** [comment]
The commands `invoke`, `logs` and `info` are now available (version `0.1.0`). The commands `create` and `install` should be supported in the `serverless` tool.

@sebgoa do you want to keep this issue opened or close it and open new ones for the other commands?

**Comment by sebgoa** [comment]
I will close. thanks, great work.
