### ISSUE TITLE
We should coordinate npm and github releases

### ISSUE THREAD

**Issue by arapulido** [serverless/serverless-kubeless#48]
I think it would be good to tag releases in Github that corresponds to the releases of the npm module (https://www.npmjs.com/package/serverless-kubeless)

Right now the version there is 0.1.8, but there are no tags in Github or releases, so it is difficult to know easily what's included and what not.

We should start creating tags and releases that correspond to the npm versions

**Comment by andresmgot** [comment]
NPM and Github releases are now automatically done with Travis. This is an example: https://github.com/serverless/serverless-kubeless/releases/tag/v0.1.12

**Comment by sebgoa** [comment]
great, looks like we can close
