### ISSUE TITLE
Ingress rule in multi-function case

### ISSUE THREAD

**Issue by sebgoa** [serverless/serverless-kubeless#66]
When deploying the todo example in GKE, several ingress rule get created.

Each one gets a public IP, that means that the frontend would need to use different targets, not a single one. So that's a bug :)

In the multi-function case we need a single ingress to be created with multiple rules in it.

**Comment by andresmgot** [comment]
@sebgoa I agree that we could deploy a multi-function scenario using just one Ingress rule but I am not able reproduce your issue having different public IPs:
```
$ kubectl get ingress
NAME               HOSTS                  ADDRESS         PORTS     AGE
ingress-create     35.185.47.240.nip.io   35.196.212.24   80        18s
ingress-delete     35.185.47.240.nip.io   35.196.212.24   80        18s
ingress-read-all   35.185.47.240.nip.io   35.196.212.24   80        18s
ingress-read-one   35.185.47.240.nip.io   35.196.212.24   80        18s
ingress-update     35.185.47.240.nip.io   35.196.212.24   80        28s
```
Anyway, I will improve the logic and the instructions to the TODO example.

**Comment by sebgoa** [comment]
are you on GKE ?

**Comment by andresmgot** [comment]
yes, I created a fresh cluster for the test
