### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by andresmgot** [serverless/serverless-kubeless#7]
Cover the code with unit tests

**Comment by andresmgot** [comment]
The code is now covered with unit tests:
```
=============================== Coverage summary ===============================
Statements   : 92.4% ( 243/263 )
Branches     : 79.55% ( 70/88 )
Functions    : 88.46% ( 23/26 )
Lines        : 93.39% ( 240/257 )
================================================================================
```

**Comment by sebgoa** [comment]
great. let's close this issue, to be fancy we could display a badge on the README which shows the coverage percentage.

**Comment by andresmgot** [comment]
Thank you. The coverage badge requires integration with https://coveralls.io so I don't think it would be needed right now. We can open a different issue for that anyway if you think it is important.
