### ISSUE TITLE
environment variables support

### ISSUE THREAD

**Issue by skunkwerk** [serverless/serverless-kubeless#88]
I didn't see any documentation for serverless variables, such as exist with AWS, example:

provider:
    name:aws
    environment:
        PUBSUB_KEY: pubsub_admin_key.json
        EVENTS_TOPIC: events

Is the passing of environment variables in this manner supported?

thanks

**Comment by skunkwerk** [comment]
This seems to be supported via k8s variables, but isn't documented.  Would be great to add this section to the serverless docs.

**Comment by sebgoa** [comment]
right, `requirements.txt` and env variables, as well as function timeout and memory limit are all supported, but the docs are lagging

**Comment by ryuheechul** [comment]
Yeah, I think docs are needed to be updated. 
for me, [this section](https://serverless.com/framework/docs/providers/aws/guide/variables/) worked for kubeless, too.

And I'm writing an open source tool using kubeless and serverless so I will put the link of the code here once that code becomes available online.

**Comment by andresmgot** [comment]
The same than #94: Documentation updates has been merged in serverless/serverless#4666

**Comment by JSNHARSHA** [comment]
The Environment variables described under 'Provider' are still not accessible in the function handler. Is this still an issue?

**Comment by andresmgot** [comment]
@JSNHARSHA that should indeed work. Are you using the latest version of the `serverless-plugin`? Can you paste here the yaml you are trying to deploy?
