### ISSUE TITLE
python requirements.txt

### ISSUE THREAD

**Issue by skunkwerk** [serverless/serverless-kubeless#91]
How do I pass the requirements.txt via serverless to kubeless?
Can I install Python modules with native dependencies, like psycopg2?

**Comment by skunkwerk** [comment]
The answer seems to be 'yes', but isn't documented.

**Comment by vishweshwarp** [comment]
@skunkwerk were you able to deploy your functions having dependencies defined in requirements.txt?

Do you have any working example? I am facing issue #97

**Comment by chipironcin** [comment]
Hello :wave: 

Our documentation does need some improvements.

In the following incubator function you can find an example of using `requirements.txt` and Python:
https://github.com/kubeless/functions/blob/master/incubator/kafka-connect/README.md#user-content-1-deploy

Our team will look at this soon and will be able to answer the question in a more concise way and document what is missing.

**Comment by andresmgot** [comment]
Documentation updates has been merged in https://github.com/serverless/serverless/pull/4666 

It will appear in the serverless docs site soon. Let us known if anything else requires further explanation.
