### ISSUE TITLE
deploying multiple Python modules

### ISSUE THREAD

**Issue by skunkwerk** [serverless/serverless-kubeless#94]
How do I deploy non-trivial Python code, which has multiple Python modules?
Example:
the function is in handler.py
but handler.py imports from models.py

Currently, the deploy fails because it doesn't include models.py.

How do I tell it to include the models.py file?

**Comment by sebgoa** [comment]
thanks for all the issues @skunkwerk , a few of us are taking a break right now so we may be a bit late to respond to your issues.

technically you should be able to provide a zip file that contains all the files needed

please bare with us.

**Comment by andresmgot** [comment]
This is now possible with the versions`^0.3.0`. Let us know if you find any trouble with that. The documentation updates are under review but will be soon available in https://serverless.com/framework/docs/providers/kubeless/guide/
