### ISSUE TITLE
Example Todo app backend can not be deployed. 

### ISSUE THREAD

**Issue by rajesh2011** [serverless/serverless-kubeless#99]
Using minikube env.
backend/README.md suggests using below url to deploy mongodb.
Unable to deploy mongodb because 
https://raw.githubusercontent.com/bitnami/bitnami-docker-mongodb/master/kubernetes.yml
is not present.

Is there a new location?

thanks

**Comment by vishweshwarp** [comment]
Yes, even I noticed same issue while deploying Todo app backend.  I used helm to deploy MongoDB https://github.com/kubernetes/charts/tree/master/stable/mongodb

But you might need to update database connection URL, username and password in example for it to work.

**Comment by andresmgot** [comment]
Sorry, that manifest has been unpublished. In our CI we are using `https://raw.githubusercontent.com/bitnami/bitnami-docker-mongodb/3.4.7-r0/kubernetes.yml`. I will update the documentation to point to that manifest for the moment.
